import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar';
import Link from 'next/link'
import Grid from '@material-ui/core/Grid';
import Landin from '../src/Images/landin.png'
import Footer from '../components/Footer';
import CheckCircleIcon from '@material-ui/icons/CheckCircle';
import { green } from '@material-ui/core/colors';
import Button from '@material-ui/core/Button';
import React, { useEffect } from 'react';
import { useRouter } from 'next/router'

export default function Home({ token }) {
  const router = useRouter();
  const [hasUser, setHasUser] = React.useState();
    useEffect(() => {
      // Evan: IF no token and no currUser THEN remove currUser (cleanup)
      if (!token && localStorage.getItem('currUser') !== null && 
      JSON.parse(localStorage.getItem('currUser')) !== "") {
        localStorage.removeItem("currUser");
      }
      // setHasUser(localStorage.getItem('currUser') !== null && 
      // JSON.parse(localStorage.getItem('currUser')) !== "" && token)
      }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>ProctorUTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ProctorUTS2.png" />
      </Head>
      <Navbar token={ token }></Navbar>
      <div className={styles.header}>

        <main className={styles.main}>
          <Grid container className={styles.Grid}>
            <Grid item xs={12} md={6}>
              <div className={styles.mainText}>
                <h1>Anti-Cheating AI <br />for <span>students</span><br />taking online exams.</h1>
                <p>Our most secure solution blends our technology solutions with human supervision, including a live proctored launch, continuous monitoring, active proctor intervention to stop suspicious behavior, comprehensive reporting and more. Essential for high-stakes programs looking to prevent cheating at UTS.</p>
                <div className={styles.buttonN}>
                  {token ?  <Button  fullWidth ={true} variant="contained" color="primary" className={styles.buttonN} onClick={() => { router.push("/dashboard") }}>
                    Go to Your Dashboard
                  </Button>: <Button variant="contained" color="primary" className={styles.buttonN} onClick={() => { router.push("/login") }}>
                    Login
                  </Button>}
                </div>
              </div>
            </Grid>

            <Grid item xs={12} md={6}>
              <div className={styles.landin}>
                <Image src={Landin} />
              </div>
            </Grid>

          </Grid>

        </main>
      </div>
      <Footer></Footer>
    </div>
  )
}

export function getServerSideProps({ req, res }) {
  return { props: { token: req.cookies.token || "" } };
}